### ISSUE TITLE
Annotating new data

### ISSUE THREAD

**Issue by ghost** [huangkuns/wireframe#21]
How to annotate new data as wireframe format. Is there any tool to do so? If there is can you please share the name?

**Comment by haak0** [comment]
Sorry for late reply. If you want to annotate new data,

- I recommend [https://github.com/wkentaro/labelme](labelme). Based on this tool, you just need to modify the pyqt code for mouse  behavior (move, click) and save function, and transform the XML format to wireframe format is quite simple.
- you can also search for tools which can annotate arbitrary polygons.

Note: our tool is modified from a similar python software, I could not find it anymore.

**Comment by huangkuns** [comment]
Sorry for late reply. If you want to annotate new data,
- I recommend https://github.com/wkentaro/labelme. Based on this tool, you just need to modify the pyqt code for mouse behavior (move, click) and save function, and transform the XML format to wireframe format is quite simple.
- you can also search for tools which can annotate arbitrary polygons.

Note: our tool is modified from a similar python software, I could not find it anymore.

**Comment by ghost** [comment]
Thank you very much for the information. I will try it.

**Comment by ily666666** [comment]
你好，请问找到您所说的标注工具了吗
