### ISSUE TITLE
Question about point coordinates

### ISSUE THREAD

**Issue by frohlichr** [huangkuns/wireframe#22]
Hi,

I would like to ask you what is the exact coordinate system in which the junction points are expressed with their (x,y) coordinates in image space? I see that the data contains both 0 and 500 values, for images with 500xN or Mx500 resolution, practically on one end or the other it is indexing outside of the image boundary, so I'm unsure what would be the exact coordinate system.
If you use OpenCV and indexing from 0, I understand that the top left corner is at [0,0] coordinate, but then where is the point with x=500 located? It's outside of the image space. What would be the correct way to interpret the data? Simply neglect values above 499?

Thank you in advance for the clarification,
Robert

**Comment by haak0** [comment]
Hi, thanks for pointing out this,
for a vertex (x, y), if x or y is outside the image range, you can just let:
x = min(max(x, 0), w-1)
y = min(max(y, 0), h-1)

**Comment by huangkuns** [comment]
hi, you can just let x = min(max(x, 0), w -1) to make x inside the image.
