### ISSUE TITLE
 data download link(invalid)

### ISSUE THREAD

**Issue by JQJ001** [huangkuns/wireframe#8]
Hello, the data download link seems to be invalid.

**Comment by huangkuns** [comment]
Hi, I checked the links, the files are valid, please retry and tell me what happened.

**Comment by GitHub0830** [comment]
Thanks for your reply. My problem has been solved.




------------------ 原始邮件 ------------------
发件人: "KUn"<notifications@github.com>;
发送时间: 2019年5月12日(星期天) 下午5:09
收件人: "huangkuns/wireframe"<wireframe@noreply.github.com>;
抄送: "ー軰孓"<497908934@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [huangkuns/wireframe]  data download link(invalid) (#8)




Hi, I checked the links, the files are valid, please retry and tell me what happened.

**Comment by JQJ001** [comment]
> Hi, I checked the links, the files are valid, please retry and tell me what happened.

Thanks for your reply. My problem has been solved.
